// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6W4dCdErT4uhf9w15g3Y7ZRNmSjULOSY',
    appId: '1:999199157459:web:55007bab7fbb033dccb826',
    messagingSenderId: '999199157459',
    projectId: 'forcen-6e2cb',
    authDomain: 'forcen-6e2cb.firebaseapp.com',
    storageBucket: 'forcen-6e2cb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcdUI2crXKJuWkrafMgxfK_yXE9CXJOKE',
    appId: '1:999199157459:android:24f7abf7e058a6e0ccb826',
    messagingSenderId: '999199157459',
    projectId: 'forcen-6e2cb',
    storageBucket: 'forcen-6e2cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp33Myw57RW8FPYCqTDUPXxgbKincQRzA',
    appId: '1:999199157459:ios:baba83c23c5cfab9ccb826',
    messagingSenderId: '999199157459',
    projectId: 'forcen-6e2cb',
    storageBucket: 'forcen-6e2cb.firebasestorage.app',
    iosBundleId: 'sn.forcen.forcen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp33Myw57RW8FPYCqTDUPXxgbKincQRzA',
    appId: '1:999199157459:ios:baba83c23c5cfab9ccb826',
    messagingSenderId: '999199157459',
    projectId: 'forcen-6e2cb',
    storageBucket: 'forcen-6e2cb.firebasestorage.app',
    iosBundleId: 'sn.forcen.forcen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6W4dCdErT4uhf9w15g3Y7ZRNmSjULOSY',
    appId: '1:999199157459:web:056f65461d7f53c3ccb826',
    messagingSenderId: '999199157459',
    projectId: 'forcen-6e2cb',
    authDomain: 'forcen-6e2cb.firebaseapp.com',
    storageBucket: 'forcen-6e2cb.firebasestorage.app',
  );
}
